stages:
  train:
    cmd: Rscript pipeline/01-train.R
    deps:
    - input/training_data.parquet
    params:
    - cv
    - model
    - toggle.cv_enable
    outs:
    - output/intermediate/model_test.parquet
    - output/parameter_final/model_parameter_final.parquet
    - output/parameter_range/model_parameter_range.parquet
    - output/parameter_search/model_parameter_search.parquet
    - output/workflow/fit/model_workflow_fit.zip
    - output/workflow/recipe/model_workflow_recipe.rds
